# Generated by Django 6.1.1 on 2026-09-21 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circunscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Circunscripción')),
                ('autoridad_local', models.CharField(max_length=150, verbose_name='Presidente / Autoridad')),
                ('enlace_oficial', models.URLField(blank=True, null=True, verbose_name='Enlace Oficial (Link)')),
                ('direccion', models.CharField(blank=True, max_length=200, verbose_name='Dirección Física')),
                ('telefono', models.CharField(blank=True, max_length=50, verbose_name='Teléfono de Contacto')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo Electrónico')),
            ],
            options={
                'verbose_name': 'Circunscripción',
                'verbose_name_plural': 'Circunscripciones',
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título de la Noticia')),
                ('contenido', models.TextField(verbose_name='Contenido de la Circular / Noticia')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Publicación')),
                ('foto_principal', models.ImageField(blank=True, null=True, upload_to='noticias/', verbose_name='Foto Principal')),
            ],
            options={
                'verbose_name': 'Noticia / Circular',
                'verbose_name_plural': 'Noticias y Circulares',
                'ordering': ['-fecha_publicacion'],
            },
        ),
    ]
