# Generated by Django 6.1.1 on 2026-09-21 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_institucional', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaEmergente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del Comunicado Urgente')),
                ('contenido', models.TextField(verbose_name='Texto de la Alerta / Información')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='alertas/', verbose_name='Imagen del Cartel (Opcional)')),
                ('activo', models.BooleanField(default=False, verbose_name='¿Mostrar este cartel en la web ahora mismo?')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Alerta Emergente (Pop-up)',
                'verbose_name_plural': 'Alertas Emergentes (Pop-up)',
            },
        ),
    ]
