# Generated by Django 6.1.1 on 2026-09-28 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_institucional', '0002_alertaemergente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autoridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200, verbose_name='Nombre Completo')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo / Función')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='autoridades/', verbose_name='Foto de Perfil')),
                ('orden_visual', models.IntegerField(default=0, verbose_name='Orden de aparición')),
            ],
            options={
                'verbose_name': 'Autoridad / Miembro Directivo',
                'verbose_name_plural': 'Comisión Directiva - Autoridades',
                'ordering': ['orden_visual'],
            },
        ),
    ]
