# Generated by Django 6.1.1 on 2026-10-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_institucional', '0003_autoridad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reglamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del Reglamento / Estatuto')),
                ('archivo_pdf', models.FileField(upload_to='reglamentos/', verbose_name='Archivo PDF Oficial')),
                ('fecha_subida', models.DateField(auto_now_add=True, verbose_name='Fecha de publicación')),
            ],
            options={
                'verbose_name': 'Reglamento / Estatuto',
                'verbose_name_plural': 'Estatutos y Reglamentos Oficiales',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
