# Generated by Django 6.1.1 on 2026-10-02 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_institucional', '0004_reglamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Misión y Función', max_length=200, verbose_name='Título de la Sección')),
                ('contenido', models.TextField(verbose_name='Texto Institucional / Leyes de Creación')),
                ('fecha_actualizacion', models.DateField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Texto de Misión y Función',
                'verbose_name_plural': 'Contenido de Misión y Función',
            },
        ),
    ]
