# Generated by Django 6.1.1 on 2026-10-09 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_institucional', '0005_institucional'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbogadoMatriculado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=150, verbose_name='Nombre Completo')),
                ('matricula', models.CharField(max_length=50, unique=True, verbose_name='Número de Matrícula (Tomo/Folio)')),
                ('circunscripcion', models.CharField(choices=[('I', 'I - Capital'), ('II', 'II - Goya'), ('III', 'III - Curuzú Cuatiá'), ('IV', 'IV - Paso de los Libres'), ('V', 'V - Santo Tomé')], max_length=5, verbose_name='Circunscripción')),
                ('correo_electronico', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('esta_validado', models.BooleanField(default=False, verbose_name='Cuenta Validada por Mail')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Abogado Registrado',
                'verbose_name_plural': 'Observatorio - Padrón de Abogados',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='VotoEncuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_semestral', models.CharField(max_length=30, verbose_name='Período (Ej: 2026-2S)')),
                ('circunscripcion_juzgado', models.CharField(max_length=5, verbose_name='Circunscripción del Juzgado')),
                ('fuero_afectado', models.CharField(max_length=50, verbose_name='Fuero con Mayor Retraso')),
                ('calificacion_global', models.CharField(choices=[('A', 'Óptimo / Satisfactorio'), ('B', 'Regular / Necesita Reformas'), ('C', 'Deficiente / Colapso Institucional')], max_length=1, verbose_name='Calificación del Juzgado')),
                ('fecha_voto', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Voto Anónimo del Observatorio',
                'verbose_name_plural': 'Observatorio - Bolsa de Votos Anónimos',
            },
        ),
    ]
